##############################################################################
# Create an object store with ldap integration for a test environment. Only a
# single OSD is required in this example.
#
# kubectl create -f object-ldap-test.yaml
##############################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: my-store-ldap
  namespace: rook-ceph
stringData:
  password: Not@SecurePassw0rd
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store-ldap
  namespace: rook-ceph # namespace:cluster
spec:
  metadataPool:
    replicated:
      size: 1
  dataPool:
    replicated:
      size: 1
  preservePoolsOnDelete: false
  gateway:
    port: 80
    # securePort: 443
    instances: 1
  ldap:
    uri: ldap://openldap.openldap.svc.cluster.local:389
    binddn: cn=admin,dc=example,dc=org
    searchdn: dc=example,dc=org
    dnattr: uid
    credentialsecret: my-store-ldap
